globalsolar/basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.cart_detail, name="cart_detail"),
    path('add/<int:product_id>/', views.cart_add, name="cart_add"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove")
    
]
# <int:product_id>

globalsolar/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="catalog"),
    path('<int:product_id>/', views.product, name="product"),

    path('ReadySolutions', views.ReadySolutions, name="ReadySolutions"),
    path('Autonomous', views.Autonomous, name="Autonomous"),
    path('OwnConsumption', views.OwnConsumption, name="OwnConsumption"),
    path('WaterHeating', views.WaterHeating, name="WaterHeating"),

    path('SolarInverters', views.SolarInverters, name="SolarInverters"),
    path('AutonomousInverters', views.AutonomousInverters,
         name="AutonomousInverters"),
    path('HybridInverters', views.HybridInverters, name="HybridInverters"),
    path('NetworkInverters', views.NetworkInverters, name="NetworkInverters"),

    path('SolarPanels', views.SolarPanels, name="SolarPanels"),
    path('monocrystalline', views.monocrystalline, name="monocrystalline"),
    path('polycrystalline', views.polycrystalline, name="polycrystalline"),
]

globalsolar/contacts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('contact/', views.contact, name="contact"),
]

globalsolar/globalsolar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('basket/', include('basket.urls', namespace='basket')),
    path('', include('solar_pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('contacts/', include('contacts.urls')),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

globalsolar/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

globalsolar/basket/models.py
from django.db import models

# Create your models here.

globalsolar/catalog/models.py
from django.db import models
from datetime import datetime
from django.conf import settings


class Catalog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    catalog_type = models.CharField(max_length=30)
    power = models.CharField(max_length=30)
    price = models.IntegerField()
    made = models.CharField(max_length=50)
    weight = models.CharField(max_length=50)
    size = models.CharField(max_length=50)
    guarantee = models.CharField(max_length=50)
    is_published = models.BooleanField(default=True)
    photo_0 = models.ImageField(upload_to="photos/%Y/%m/%d/")
    photo_1 = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True)
    photo_2 = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True)
    photo_3 = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True)

    def __str__(self):
        return self.title

globalsolar/contacts/models.py
from django.db import models
from datetime import datetime


class Contact(models.Model):
    title = models.CharField(max_length=250)
    work_id = models.IntegerField()
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    message = models.TextField(blank=True)
    address = models.CharField(max_length=200, blank=True)
    date = models.DateTimeField(default=datetime.now, blank=True)
    user_id = models.IntegerField(blank=True)

    def __str__(self):
        return self.name

globalsolar/basket/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

globalsolar/basket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Catalog
from django.urls import reverse
from .forms import CartAddProductForm
from .basket import Basket

# def index(request, product_id):
#     product = get_object_or_404(Catalog, pk=product_id)
#     context = {
#         "product": product,
#     }
#     return render(request, 'pages/basket.html', context)

@require_POST
def cart_add(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Catalog, pk=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        basket.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('basket:cart_detail')

def cart_remove(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Catalog, id=product_id)
    basket.remove(product)
    return redirect('basket:cart_detail')

def cart_detail(request):
    basket = Basket(request)
    for item in basket:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'],'update': True})
    return render(request, 'pages/basket.html', {"basket": basket})

globalsolar/catalog/views.py
from django.shortcuts import render, redirect
from .models import Catalog
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.db.models import Q
from . import views
from basket.forms import CartAddProductForm

def index(request):
    catalog_prod = Catalog.objects.all()
    paginator = Paginator(catalog_prod, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    
    context = {
        "catalog": page,
    }
    return render(request, "pages/catalog.html", context)




def product(request, product_id):
    product = get_object_or_404(Catalog, pk=product_id)
    cart_product_form = CartAddProductForm()
    context = {
        "product": product,
        'cart_product_form':cart_product_form,
    }
    return render(request, "pages/product.html", context)

def SolarPanels(request):
    SolarPanels = Catalog.objects.all().filter(Q(catalog_type='monocrystalline') | Q(catalog_type='polycrystalline') | Q(catalog_type='SolarPanels'))
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/catalogPage.html", context)

def monocrystalline(request):
    SolarPanels = Catalog.objects.all().filter(Q(catalog_type='monocrystalline') | Q(catalog_type='SolarPanels'))
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/catalogMono.html", context)
    
def polycrystalline(request):
    SolarPanels = Catalog.objects.all().filter(Q(catalog_type='polycrystalline') | Q(catalog_type='SolarPanels'))
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/catalogPoly.html", context)

def ReadySolutions(request):
    SolarPanels = Catalog.objects.all().filter(Q(catalog_type='Autonomous') | Q(catalog_type='OwnConsumption') | Q(catalog_type='WaterHeating'))
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/ReadySolutions.html", context)

def Autonomous(request):
    SolarPanels = Catalog.objects.all().filter(catalog_type='Autonomous')
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/Autonomous.html", context)

def OwnConsumption(request):
    SolarPanels = Catalog.objects.all().filter(catalog_type='OwnConsumption')
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/OwnConsumption.html", context)

def WaterHeating(request):
    SolarPanels = Catalog.objects.all().filter(catalog_type='WaterHeating')
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/WaterHeating.html", context)

def SolarInverters(request):
    SolarPanels = Catalog.objects.all().filter(Q(catalog_type='AutonomousInverters') | Q(catalog_type='HybridInverters') | Q(catalog_type='NetworkInverters'))
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/SolarInverters.html", context)

def AutonomousInverters(request):
    SolarPanels = Catalog.objects.all().filter(catalog_type='AutonomousInverters')
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/AutonomousInverters.html", context)

def HybridInverters(request):
    SolarPanels = Catalog.objects.all().filter(Q(catalog_type='AutonomousInverters') | Q(catalog_type='HybridInverters'))
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/HybridInverters.html", context)

def NetworkInverters(request):
    SolarPanels = Catalog.objects.all().filter(catalog_type='NetworkInverters')
    
    paginator = Paginator(SolarPanels, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "SolarPanels": page,
    }
    return render(request, "pages/catalog/NetworkInverters.html", context)

globalsolar/contacts/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from .models import Contact


def contact(request):
    if request.method == "POST":
        name = request.POST["name"]
        work_title = request.POST["work_title"]
        email = request.POST["email"]
        phone = request.POST["phone"]
        address = request.POST["address"]
        message = request.POST["message"]
        work_id = request.POST["work_id"]

        if request.user.is_authenticated:
            user_id = request.user.id
            contact = Contact.objects.all().filter(
                work_id=work_id, user_id=user_id
            )
            if contact:
                print("contact added")
                return redirect('/portfolio/' + work_id)
        contact = Contact(title=work_title, work_id=work_id, name=name, email=email,
                          phone=phone, message=message, address=address, user_id=request.user.id)
        contact.save()

        send_mail(
            "New connect",
            "Станція:" + " " + work_title + " " + "контакт з новим клієнтом" +
            message + " " + name + " " + email + " " + phone,
            'sup2a1nn@gmail.com',
            ['sup2a1nn@gmail.com'],# Теж ваша електронка - куди буде лист відправлятися
            fail_silently=False
        )

        return redirect('/portfolio/' + work_id)

globalsolar/templates/pages/about_us.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main>
  <div class="container-fluid about">
    <div class="container">
      <div class="row">
        <div class="header col-12">
          <h1>Про нас</h1>
          <hr />
          <p>
            Спеціалізацією нашої компанії «Солар Систем» є монтаж, реалізація,
            сервісне гарантійне та післягарантійне обслуговування сонячних
            електростанцій та сонячних колекторів будь-якої складності та
            потужності. Займаємось:
          </p>
        </div>
        <section class="content col-12">
          <p>
            Спираючись на успішний досвід реалізації понад 100 проектів в сфері
            альтернативної енергетики, за останні 5 років, для кожного нашого
            клієнта ми гарантуємо: розробка кожного проекту здійснюється
            професійним інженером з використанням спеціалізованих програм
            PVSyst, FroniusSolarConfigurator, що дає можливість на підготовчому
            етапі спрогнозувати, з яким результатом буде працювати СЕС та
            скільки принесе доходу.<br />
            Mонтаж сонячних панелей виконується спеціалістами покрівельниками,
            які досконало розуміються на всіх конструктивних тонкощах висотних
            та покрівельних робіт, з реальним портфоліо понад 400 об’єктів.
            Відповідно ми надаємо повну гарантію терміном 2 роки на всі
            будівельно-монтажні роботи.
          </p>
        </section>
        <section class="our_ambition col-12">
          <div class="row">
            <div class="img col-5">
              <img src="{{STATIC_PREFIX}}img/about/work.png" />
            </div>
            <div class="col-6 offset-1">
              <div class="col-12 ambition_middle">
                <div class="row">
                  <div class="col-5 ambition_border">
                    <img src="{{STATIC_PREFIX}}img/about/team.png" alt="" />
                    <div class="row">
                      <h4>
                        Наша амбіція — <br />направити енергію сонця в кожний
                        дім.
                      </h4>
                    </div>
                  </div>
                  <div class="col-7 ambition_text">
                    <p>
                      Тому що сонце — це суперджерело, яке здатне зробити
                      будинок кращою версією себе: розумним, екологічним,
                      контрольованим та вигідним.
                    </p>
                  </div>
                </div>
              </div>
              <p class="text_out">
                Ми пропонуємо економічні та прості в використанні технологічні
                рішення. Ми поважаємо своїх клієнтів, їх час та комфорт, тому ми
                на зв’язку 24/7 і завжди готові відповідати на будь-які питання
                та проводити сервісне обслуговування обладнання.
              </p>
            </div>
          </div>
        </section>
        <section class="our_methods col-12">
          <div class="row">
            <div class="methods col-7">
              <h5>Наші методи зрозумілі та ефективні:</h5>
              <ul>
                <li>
                  Щоб забезпечити наших клієнтів офіційною гарантією від
                  виробника та оптимальними цінами, ми уклали прямі договори з
                  постачальниками обладнання.
                </li>
                <li>
                  Ми сформували власні монтажні команди для того, щоб повністю
                  відповідати за результат роботи.
                </li>
                <li>
                  Для того, щоб наш сервіс завжди був вчасним, ми створили
                  власний склад і вантажний автопарк.
                </li>
              </ul>
            </div>
            <div class="col-5">
              <img src="{{STATIC_PREFIX}}img/about/work_copy.png" alt="" />
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
  <div class="container-fluid bg-advantages_us">
    <div class="container advantages">
      <div class="col-12">
        <h2>Наші переваги</h2>
        <div class="row offset-1 advantages_row_one">
          <div class="col-5 p-0">
            <img src="{{STATIC_PREFIX}}img/img/01.png" alt="" />
            <h3>Розробка проекту "під ключ"<span>01</span></h3>
            <p>
              Комплексний підхід дає відповіді на питання: скільки буде
              коштувати обладнання, який дохід принесе СЕС, 3D макет всіх
              конструктивних елементів, розрахунок всіх поточних витрат
              пов'язаних з реалізацією проекту
            </p>
          </div>
          <div class="col-5 offset-1 p-0">
            <img src="{{STATIC_PREFIX}}img/img/02.png" alt="" />
            <h3>Технічна підтримка 24/7/365<span>02</span></h3>
            <p>
              Інженери компанії пройшли спеціалізоване навчання від провідних
              світових виробників - Fronius та Huawei, це дозволяє вирішувати
              нестандартну ситуацію в роботі обладнання терміном до 48 годин
            </p>
          </div>
        </div>
        <div class="row offset-1 p-0">
          <div class="col-5">
            <img src="{{STATIC_PREFIX}}img/img/03.png" alt="" />
            <h3>Он-лайн моніторинг<span>03</span></h3>
            <p>
              Постійно відслідковуючи роботу всіх СЕС, що підключені до
              інтернету, ми контролюємо надійність та продуктивність роботи
              встановленого обладнання у форматі 24/7, з гарантією на виконані
              роботи 2 роки
            </p>
          </div>
          <div class="col-5 offset-1 p-0">
            <img src="{{STATIC_PREFIX}}img/img/04.png" alt="" />
            <h3>Сертифіковане обладнання<span>04</span></h3>
            <p>
              Використовуючи лише сертифіковане обладанання та комплектуючі
              провідних світових виробників, ми надаємо 2 роки гарантії на
              виконані монтажні роботи та повну гарантію від заводу виробника
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid bg-scheme">
    <div class="container scheme">
      <div class="col-12">
        <div class="row">
          <img
            class="img_scheme col-7"
            src="{{STATIC_PREFIX}}img/about/Vlasne_spozhyvannya_schema-1024x613.png"
          />
          <div class="resources col-5">
            <p>
              <span>Наш головний ресурс</span> — це команда професіоналів, тому
              ми цінуємо кожного, з ким працюємо. Ми постійно підвищуємо
              кваліфікацію членів команди: від керівників відділів до
              інсталяторів. Тільки так досягається найкращий результат.
            </p>
            <p>
              Закони ринку гарантують зростання пропозиції при умові такого
              великого попиту. Сьогодні знайти компанію, яка готова встановити
              сонячні панелі на даху вашого будинку можна за лічені секунди.
              Робити бізнес від продажу та монтажу обладнання під “зелений
              тариф” кинулися всі. Вчорашні юристи, продавці та студенти активно
              пропонують свої послуги. Споживачу складно оцінити рівень
              кваліфікації підрядника, та й не заведено в нашій країні ретельно
              перевіряти контрагента.
            </p>

            <p>
              Спорудження об’єктів електроенергетики ― це відповідальна галузь,
              що потребує професійного підходу. Помилки можуть коштувати дорого:
              загроза працездатності станції, небезпека виникнення пожежі, та
              навіть загроза життю і здоров’ю людей.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid video">
    <div class="container">
      <iframe
        class="col-12"
        width="1349"
        height="480"
        src="https://www.youtube.com/embed/NLO9w963Aj0"
        frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
      ></iframe>
    </div>
  </div>
</main>
{% endblock %}

globalsolar/templates/pages/basket.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid bg-basket">
    <div class="container bascket">
        <div class="co-12 descr">
            <div class="row">
                <div class="col-2 offset-6"><h3>Кількість</h3></div>
                <div class="col-2"><h3>Ціна за 1 товар</h3></div>
                <div class="col-2"><h3>Ціна</h3></div>
            </div>
        </div>
            {% for item in basket %}
            {% with product=item.product %}
        <div class="col-12 basket-product">
            <div class="row">
                <div class="col-2">
                    <img class="basket_photo" src="{{ product.photo_0.url }}" alt="">
                </div>
                <div class="col-4">
                    <h2 class="basket_tile">{{ product.title }}</h2>
                </div>
                <div class="col-2">
                        <form action="{% url 'basket:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" class="btn-danger" value="Обновить">
                            {% csrf_token %}
                    </form>
                </div>
                <div class="col-2">
                    <h2 class="basket_price_p">${{ item.price }}</h2>
                </div>
                <div class="col-2">
                    <h2 class="basket_price_t">{{ item.total_price }}$</h2>
                    <form action="{% url 'basket:cart_remove' product.id%}">
                        <button class="btn-danger btn_remove">Видалити</button>
                    </form></div>
            </div></div>
            {% endwith %}
        {% endfor %}
        
        <div class="col-4 offset-8 busket_button">
                <h2 class="basket_price">{{ basket.get_total_price }}$</h2>
                <form action="{% url 'orders:order_create' %}">
                    <button class="btn-danger btn_of">Oформити замовлення</button>
                </form>
        </div>
    </div>
</div>
{% endblock %}

globalsolar/templates/pages/catalog.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid bg-catalog">
  <div class="container catalog">
    <div class="row">
      <div class="col-3">
        <div class="col-12 category pl-0 pr-0">
          <div class="col-12 category_t p-0">
            <h2>категорії</h2>
          </div>
          <ul>
            <h3><a href="{% url 'ReadySolutions' %}">Готові рішення</a></h3>
            <hr />
            <li><a href="{% url 'Autonomous' %}">Автономні</a></li>
            <li><a href="{% url 'OwnConsumption' %}">Власне споживання</a></li>
            <li><a href="{% url 'WaterHeating' %}">Підігрів води</a></li>
          </ul>
          <ul>
            <h3><a href="{% url 'SolarInverters' %}">Сонячні інвертори</a></h3>
            <hr />
            <li><a href="{% url 'AutonomousInverters' %}">Автономні</a></li>
            <li><a href="{% url 'HybridInverters' %}">Гібридні (з АКБ)</a></li>
            <li><a href="{% url 'NetworkInverters' %}">Мережеві (зелений тариф)</a></li>
          </ul>
          <ul>
            <h3><a href="{% url 'SolarPanels' %}">Сонячні панелі</a></h3>
            <hr />
            <li><a href="{% url 'monocrystalline' %}">Монокристалічні</a></li>
            <li><a href="{% url 'polycrystalline' %}">Полікристалічні</a></li>
          </ul>
        </div>
      </div>
      <div class="catalog_tovaru col-9">
          {% if catalog %}
        <div class="row">
            {% for product in catalog %}
          <div class="col-4">
            <a href="{% url 'product' product.id  %}">
              <div class="price_black">
                <div class="col-12 price_black_top p-0">
                  <h2>{{ product.power }}</h2>
                </div>
                <div class="price_black_bottom col-12 p-0" style="background-image: url('{{ product.photo_0.url }}')">
                  <div class="bottom col-12">
                    <p class="info_catalog">{{ product.title }}</p>
                    <p class="price_catalog">{{ product.price }}$</p>
                  </div>
                </div>
              </div>
            </a>
          </div>
            {% endfor %}
        </div>
        <div class="row" id="pagin">
            <div class="col-12">
              <nav
                class="navigation pagination"
                role="navigation"
                aria-label="Навігація записів"
              >
                <h2 class="screen-reader-text">Навігація записів</h2>
                <div class="nav-links">
                    {% for i in catalog.paginator.page_range %}
                    {% if i == catalog.number %}
                  <a class="page-numbers " style="color:red;" href="?page={{i}}">{{i}}</a>
                  {% else %}
                  <a class="page-numbers" href="?page={{i}}">{{i}}</a>
                  {% endif %}
                  {% endfor %}  
                </div>
              </nav>
            </div>
          </div>
      </div>
        {% else %}
            <div>Нічого не знайдено</div>
            {% endif %}
        
      </div>
    </div>
  </div>
</div>
{% endblock %}

globalsolar/templates/pages/catalogPage.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid bg-catalog">
  <div class="container catalog">
    <div class="row">
      <div class="col-3">
        <div class="col-12 category pl-0 pr-0">
          <div class="col-12 category_t p-0">
            <h2>категорії</h2>
          </div>
          <ul>
            <h3><a href="#">Готові рішення</a></h3>
            <hr />
            <li><a href="#">Автономні</a></li>
            <li><a href="#">Власне споживання</a></li>
            <li><a href="#">Вуличне освітлення</a></li>
            <li><a href="#">Зелений тариф</a></li>
            <li><a href="#">Карпорт</a></li>
            <li><a href="#">Підігрів води</a></li>
          </ul>
          <ul>
            <h3><a href="#">Сонячні інвертори</a></h3>
            <hr />
            <li><a href="#">Автономні</a></li>
            <li><a href="#">Гібридні (з АКБ)</a></li>
            <li><a href="#">Мережеві (зелений тариф)</a></li>
          </ul>
          <ul>
            <h3><a href="{{ SolarPanels }}">Сонячні панелі</a></h3>
            <hr />
            <li><a href="{{ monocrystalline }}">Монокристалічні</a></li>
            <li><a href="{{ polycrystalline }}">Полікристалічні</a></li>
          </ul>
        </div>
      </div>
      <div class="catalog_tovaru col-9">
          {% if SolarPanels %}
        <div class="row">
            {% for product in SolarPanels %}
          <div class="col-4">
            <a href="{% url 'product' product.id  %}">
              <div class="price_black">
                <div class="col-12 price_black_top p-0">
                  <h2>{{ product.power }}</h2>
                </div>
                <div class="price_black_bottom col-12 p-0" style="background-image: url('{{ product.photo_1.url }}')">
                  <div class="bottom col-12">
                    <p class="info_catalog">{{ product.title }}</p>
                    <p class="price_catalog">{{ product.price }}$</p>
                  </div>
                </div>
              </div>
            </a>
          </div>
            {% endfor %}
        </div>
        <div class="row" id="pagin">
            <div class="col-12">
              <nav
                class="navigation pagination"
                role="navigation"
                aria-label="Навігація записів"
              >
                <h2 class="screen-reader-text">Навігація записів</h2>
                <div class="nav-links">
                    {% for i in catalog.paginator.page_range %}
                    {% if i == catalog.number %}
                  <a class="page-numbers " style="color:red;" href="?page={{i}}">{{i}}</a>
                  {% else %}
                  <a class="page-numbers" href="?page={{i}}">{{i}}</a>
                  {% endif %}
                  {% endfor %}  
                </div>
              </nav>
            </div>
          </div>
      </div>
        {% else %}
            <div>Нічого не знайдено</div>
            {% endif %}
        
      </div>
    </div>
  </div>
</div>
{% endblock %}

globalsolar/templates/pages/created.html
{% extends "base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}
<div class="container-fluid created-bg">
    <div class="container created">
        <h2>Дякуємо за замовлення</h2>
    <p>Ваше замовлення відправлено в обробку. Номер вашого замовлення
        <strong>{{ order.id }}</strong>.</p>
    </div>
</div>
    
{% endblock %}

globalsolar/templates/pages/product.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid bg-product">
  <div class="container product">
    <div class="col-12 product_head">
        {% csrf_token %}
      <h2>{{ product.title }}</h2>
    </div>
    <div class="row">
      <div class="col-6 product_img">
        <img class="product_img_0" src="{{ product.photo_0.url }}" alt="" />
        <div class="row">
            {% if product.photo_0 %}
            <img class="product_img_1 product_img_" src="{{ product.photo_0.url }}" alt="" />
            {% endif %}
            {% if product.photo_1 %}
            <img class="product_img_2 product_img_" src="{{ product.photo_1.url }}" alt="" />
            {% endif %}
            {% if product.photo_1 %}
            <img class="product_img_3 product_img_" src="{{ product.photo_2.url }}" alt="" />
            {% endif %}
            {% if product.photo_1 %}
            <img class="product_img_4 product_img_" src="{{ product.photo_3.url }}" alt="" />
            {% endif %}
        </div>
      </div>
      <div class="col-6 product_info">
        <p>{{ product.description }}</p>
        <ul>
          <li><span>Тип:</span> {{ product.catalog_type }}</li>
          <li><span>Вартість:</span> {{ product.price }}$</li>
          <li><span>Потужність, кВт:</span> {{ product.power }}</li>
          <li><span>Необхідна площа:</span> {{ product.size }} м2</li>
          <li><span>Вага модулів:</span>{{ product.weight }} кг</li>
          <li><span>Гарантія:</span> {{ product.guarantee }}</li>
          <li><span>Виробництво:</span> {{ product.made }}</li>
        </ul>
        </form>
        <form action="{% url 'basket:cart_add' product.id %}" method="POST">
          {{ cart_product_form }}
          {% csrf_token %}
          <button class="btn-danger">Замовити</button>
        </form>
        
      </div>
    </div>
  </div>
</div>
{% endblock %}